version: 2

models:
  - name: fct_nyc_311_performance
    description: "جدول وسيط شامل يحلل أداء الشكاوى (المغلقة والمفتوحة) وتوقيتاتها"
    columns:
      - name: complaint_id
        tests:
          - unique
          - not_null

      - name: ticket_age_days
        description: "عُمر الشكوى بالأيام (حتى تاريخ الإغلاق أو تاريخ اليوم للشكاوى المفتوحة)"
        tests:
          - dbt_utils.expression_is_true:
              arguments:
                expression: ">= 0"

      - name: is_late
        description: "مؤشر منطقي يحدد ما إذا تجاوزت الشكوى 5 أيام"
        tests:
          - not_null

      - name: is_open_backlog
        description: "يحدد ما إذا كانت الشكوى لا تزال مفتوحة"
        tests:
          - not_null

      - name: complaint_type_key
        description: "مفتاح نوع الشكوى"
        tests:
          - not_null

      - name: location_key
        description: "مفتاح موقع الشكوى"
        tests:
          - not_null

      - name: date_key
        description: "مفتاح تاريخ الشكوى"
        tests:
          - not_null

      - name: time_period
        description: "فترة اليوم التي تم تقديم الشكوى فيها"
        tests:
          - accepted_values:
              arguments:
                values: ['Morning', 'Afternoon', 'Evening', 'Night']

  # 2. الموديل الثاني (بُعد التاريخ)
  - name: dim_date
    description: "جدول أبعاد الوقت"
    columns:
      - name: date_key
        tests:
          - unique
          - not_null

  # 3. الموديل الثالث (بُعد أنواع الشكاوى)
  - name: dim_complaint_types
    description: "جدول الأبعاد لأنواع الشكاوى وتصنيفاتها"
    columns:
      - name: complaint_type_key
        tests:
          - unique
          - not_null
      - name: complaint_type
        tests:
          - unique
          - not_null
      - name: complaint_category
        description: "الفئة التي تنتمي إليها الشكوى"
        tests:
          - not_null
  - name: dim_locations
    description: "جدول الأبعاد لمواقغ الشكاوى "
    columns:
      - name: location_key
        tests:
          - unique
          - not_null