name: 'nyc_311_project'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]

models:
  nyc_311_project:
    staging:
      +materialized: table
      