name: BigQuery Connection Test
on:
  workflow_dispatch: # يتيح لكِ تشغيل الروبوت يدوياً للتجربة

jobs:
  test-connection:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # ضروري جداً لاستخدام Workload Identity

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/113456966208/locations/global/workloadIdentityPools/depi-pool/providers/github-provider'
          service_account: 'dbt-user-311@depi-graduation-project-489604.iam.gserviceaccount.com'

      - name: Test BigQuery Access
        run: |
          gcloud bw query --use_legacy_sql=false 'SELECT count(*) FROM `depi-graduation-project-489604.nyc_311_raw_data.raw_service_requests` LIMIT 10'
